= Doctool Template
:last-update-label!:

**Description**: Repository to store, contribute and showcase team documenation

**Deployed URL**: link:https://pseudo-su.github.io/doctool-template/[https://pseudo-su.github.io/doctool-template/index.html]

// BOOTSTRAP: Remove this section when bootstrapping from template
== About this template

This template pulls together various tools to make maintaining and publishing documentation from a single source controlled repository easier.

* Asciidoc - for templating link:https://asciidoctor.org/docs/asciidoc-writers-guide/[more info]
* OpenAPI (swagger) - for API documenation link:https://swagger.io/docs/specification/about/[more info]
* PlantUML - for diagrams link:https://asciidoctor.org/docs/asciidoctor-diagram/[more info]
* MxModel - for draw.io style diagrams link:https://github.com/jgraph/drawio-diagrams[examples]
* Pygments - Syntax highlighting link:http://pygments.org/languages/[supported languages]

The main goal of this project is to have as much documenation as possible tracked in a single version control system.

=== Bootstrapping TODO list

* Choose a `<project-name>` and clone this repository
+
[source, bash]
....
$ git clone git@github.com:pseudo-su/doctool-template.git <project-name>
$ cd <project-name>
....
* Find all references to `// BOOTSTRAP: <task>` comments in the project and follow their instructions
* Run `./clean.sh`
* Run `./build.sh`
* Create fresh git repo
+
[source, bash]
....
$ rm -r .git
$ git init
$ git add .
$ git commit -m 'Bootrap from pseudo-su/doctool-template'
# Optional: push to a new/empty git remote
$ git remote add origin <your-git-remote-url>
$ git push -u origin master
....

== Quick Start

1. Build
+
[source, bash]
----
# Build the builder
$ docker build -t doctool-builder ./builder
# Clean docs/
$ ./clean.sh
# Build docs/
$ ./build.sh
----

2. View
+
[source, bash]
----
$ open docs/index.html
----

== Generation rules

This project looks at all files in the `resources/` folder and generates corresponding files in the `docs/` folder depending on the filename suffix.

* `*.adoc` generates:
** `*.html`
* `*.openapi.yml` (v3) generates:
** `*.openapi.redoc.html`

NOTE: unable to geneate `*.doc.html` at the moment for openapi because swagger2markup link:https://github.com/Swagger2Markup/swagger2markup/issues/340[does not support] it (v3)

* `*.swagger.yml` (v2) generates:
** `*.swagger.redoc.html`
** `*.swagger.doc.html`
* `*.mxgraph.xml` generates:
** `*.mxgraph.html`

NOTE: You can embed the generated mxgraph html using `mxgraph::eapi.mxgraph.html[]`

== Roadmap / TODO list

* investigate switching to asciidoctor.js [ link:https://github.com/eshepelyuk/asciidoctor-plantuml.js/blob/master/README.adoc[diagrams's] | link:https://github.com/asciidoctor/asciidoctor.js/issues/102[pdf's] | link:https://github.com/asciidoctor/asciidoctor.js/issues/427[source syntax highlighting]]
* Investigate better replacement for `./build-single-mxgraph.sh` that can actually export images
* Publish the docker container instead of storing definition in `./builder/`
