= Doctool Template
:last-update-label!:

**Description**: Repository to store, contribute and showcase team documenation

**Deployed URL**: link:https://pseudo-su.github.io/doctool-template/[https://pseudo-su.github.io/doctool-template/index.html]

// BOOTSTRAP: Remove this section when bootstrapping from template
== About this template

This template pulls together various tools to make maintaining and publishing documentation from a single source controlled repository easier.

* Asciidoc - for templating link:https://asciidoctor.org/docs/asciidoc-writers-guide/[more info]
* OpenAPI (swagger) - for API documenation link:https://swagger.io/docs/specification/about/[more info]
* PlantUML - for diagrams link:https://asciidoctor.org/docs/asciidoctor-diagram/[more info]
* MxModel - for draw.io style diagrams link:https://github.com/jgraph/drawio-diagrams[examples]
* Pygments - Syntax highlighting link:http://pygments.org/languages/[supported languages]

The main goal of this project is to have as much documenation as possible tracked in a single version control system.

== Quick Start

1. Install dependencies
+
[source, bash]
----
# Asciidoctor for asciidoc and PlantUML support
$ gem install pygments.rb
$ gem install asciidoctor
$ gem install asciidoctor-diagram
$ gem install asciidoctor-pdf --pre

# Pygments for code block highlighting support
$ gem install pygments.rb

# Redoc for Openapi/Swagger support
$ npm install -g redoc-cli

## MxModel support (draw.io)
# The draw.io desktop app supports editing local mxmodel files
$ open https://github.com/jgraph/drawio-desktop/releases

# Install swagger2markup locally
# $ wget https://jcenter.bintray.com/io/github/swagger2markup/swagger2markup-cli/1.3.3/swagger2markup-cli-1.3.3.jar -O ./bin/swagger2markup.jar

# TODO: swagger2markup doesn't work for openapi v3, find/make an alternative

----

2. Build
+
[source, bash]
----
# Compile all .adoc files to .pdf
$ ./build-all.sh
----

3. View
+
[source, bash]
----
# serve static assets using web server
$ open docs/index.html
----

== Generation rules

This project looks at all files in the `resources/` folder and generates corresponding files in the `docs/` folder depending on the filename suffix.

* `*.adoc` generates:
** `*.html`
* `*.openapi.yml` (v3) generates:
** `*.openapi.redoc.html`

NOTE: unable to geneate `doc.html` at the moment because swagger2markup link:https://github.com/Swagger2Markup/swagger2markup/issues/340[does not support] openapi (v3)

* `*.swagger.yml` (v2) generates:
** `*.swagger.redoc.html`
** `*.swagger.doc.html`
* `*.mxgraph.xml` generates:
** `*.mxgraph.html`

NOTE: You can embed the generated mxgraph html using `mxgraph::eapi.mxgraph.html[]`

== Roadmap / TODO list

* investigate switching to asciidoctor.js [ link:https://github.com/eshepelyuk/asciidoctor-plantuml.js/blob/master/README.adoc[diagrams's] | link:https://github.com/asciidoctor/asciidoctor.js/issues/102[pdf's] | link:https://github.com/asciidoctor/asciidoctor.js/issues/427[source syntax highlighting]]
* Investigate better replacement for `./build-single-mxgraph.sh` that can actually export images
* Publish a docker image that obfuscates the hodge-podge of different tools from the project
+
.Example
[source, bash]
....
$ docker run \
  --mount type=bind,source=./resources,target=/input \
  --mount type=bind,source=./docs,target=/output \
  doctool-generator-imagename
....
