= Doctool Template
:last-update-label!:

Description: Repository to document and contribute to design documenation

Deployed URL: link:https://pseudo-su.github.io/doctool-template/[https://pseudo-su.github.io/doctool-template/index.html]

// BOOTSTRAP: Remove this section when bootstrapping from template
== About this template

This template pulls pulls together various tools to make maintaining a single documenation repository easier.

* Asciidoc - for templating link:https://asciidoctor.org/docs/asciidoc-writers-guide/[more info]
* PlantUML - for diagrams link:https://asciidoctor.org/docs/asciidoctor-diagram/[more info]
* MxModel - for draw.io style diagrams link:https://github.com/jgraph/drawio-diagrams[examples]

The main goal of this project is to have as much documenation as possible tracked in a single version control system.

== Quick Start

1. Install dependencies
+
[source, bash]
----
# Asciidoctor for asciidoc and PlantUML support
$ gem install pygments.rb
$ gem install asciidoctor
$ gem install asciidoctor-diagram
https://github.com/eshepelyuk/asciidoctor-plantuml.js/blob/master/README.adoc
$ gem install asciidoctor-pdf --pre

# Pygments for code block highlighting support
$ gem install pygments.rb

# Redoc for Openapi/Swagger support
$ npm install -g redoc-cli

## MxModel support (draw.io)
$ npm install -g git+https://git@github.com:languitar/drawio-batch.git
# TODO: generate html/images/svg from mxModel
# Also download this for local editing: https://github.com/jgraph/drawio-desktop/releases

# Install swagger2markup locally
# $ wget https://jcenter.bintray.com/io/github/swagger2markup/swagger2markup-cli/1.3.3/swagger2markup-cli-1.3.3.jar -O ./bin/swagger2markup.jar

# TODO: swagger2markup doesn't work for openapi v3, find/make an alternative

----

2. Build
+
[source, bash]
----
# Compile all .adoc files to .pdf
$ ./build-all.sh
----

3. Run
+
[source, bash]
----
# serve static assets using web server
$ serve -s docs
----

== Generation rules

This project looks at all files in the `resources/` folder and generates corresponding files in the `docs/` folder depending on the filename suffix.

* `*.adoc` generates:
** `*.html`
* `*.openapi.yml` (v3) generates:
** `*.openapi.redoc.html`

NOTE: unable to geneate `doc.html` at the moment because swagger2markup link:https://github.com/Swagger2Markup/swagger2markup/issues/340[does not support] openapi (v3)

* `*.swagger.yml` (v2) generates:
** `*.swagger.redoc.html`
** `*.swagger.doc.html`
* `*.mxgraph.xml` generates:
** `*.mxgraph.html`

NOTE: You can embed the generated mxgraph html using `mxgraph::eapi.mxgraph.html[]`
