= Example Documentation Website
:last-update-label!:
:source-highlighter: pygments

== Onboarding and overview

* link:onboarding/overview.html[Architecture overview]
* link:onboarding/machine-setup.html[Machine Setup]
* link:onboarding/glossary.html[Glossary]

== Openapi Contracts

* Simple Openapi - [ link:openapi-contracts/simple.openapi.redoc.html[redoc] ]
* Simple Swagger - [ link:openapi-contracts/simple.swagger.redoc.html[redoc] | link:openapi-contracts/simple.swagger.doc.html[html doc] ]
* Expanded Openapi - [ link:openapi-contracts/expanded.openapi.redoc.html[redoc] ]
* Expanded Swagger - [ link:openapi-contracts/expanded.swagger.redoc.html[redoc] | link:openapi-contracts/expanded.swagger.doc.html[html doc] ]


== Architectural Decision Records

* link:decision-records/0001/0001-example-decision-record.html[0001 Example decision record]

== Miscellaneous Docs

* link:misc/some-feature/workflow.html[Some Feature Workflow]

== Examples

.Ditaa Diagram
[ditaa]
....
                   +-------------+
                   | Asciidoctor |-------+
                   |   diagram   |       |
                   +-------------+       | PNG out
                       ^                 |
                       | ditaa in        |
                       |                 v
 +--------+   +--------+----+    /---------------\
 |        | --+ Asciidoctor +--> |               |
 |  Text  |   +-------------+    |   Beautiful   |
 |Document|   |   !magic!   |    |    Output     |
 |     {d}|   |             |    |               |
 +---+----+   +-------------+    \---------------/
     :                                   ^
     |          Lots of work             |
     +-----------------------------------+
....

.PlantUML Diagram
[plantuml, diagram-classes, png]     
....
class BlockProcessor
class DiagramBlock
class DitaaBlock
class PlantUmlBlock

BlockProcessor <|-- DiagramBlock
DiagramBlock <|-- DitaaBlock
DiagramBlock <|-- PlantUmlBlock
....

.Example using C4-PlantUML
[plantuml, diagram]
....
@startuml C4_Elements
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Container.puml

Person(personAlias, "Label", "Optional Description")
Container(containerAlias, "Label", "Technology", "Optional Description")
System(systemAlias, "Label", "Optional Description")

Rel(personAlias, containerAlias, "Label", "Optional Technology")
@enduml
....

.Javascript code snippet
[source, javascript]     
....
const example = {};
const example2 = {};

function myFunction() {
    // This makes no sense
    console.log(example);
    return example2;
}
....

.Bash code snippet
[source, bash]
----
# serve static assets using web server
$ ./run-some-command ./inputfile.txt ./outputfile.txt
----
